// Project Euler: Problem 2: Even Fibonacci Numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, 
// find the sum of the even-valued terms.

function fiboEvenSum(n) {
  let fibo = [1, 2];
  while (fibo.length < n) {
    let addend1 = fibo[fibo.length - 1];
    let addend2 = fibo[fibo.length - 2];
    fibo.push(addend1 + addend2);
  }
  let sum = 0;
  for (let i = 0; i < fibo.length; i++) {
    if (fibo[i] <= n && fibo[i] % 2 === 0) {
      sum += fibo[i];
    }
  }
  return sum;
}